apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: e2esa-webapp01-ns
  name: e2esa-webapp01-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: e2esa-webapp01
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: e2esa-webapp01
    spec:
      serviceAccountName: e2esa-service-account-01
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: e2esa-webapp01-img
        ports:
        - containerPort: 80
