---
apiVersion: v1
kind: Namespace
metadata:
  name: e2esa-webapp01-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: e2esa-webapp01-ns
  name: e2esa-webapp01-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: e2esa-webapp01
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: e2esa-webapp01
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: e2esa-webapp01-img
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: e2esa-webapp01-ns
  name: e2esa-webapp01-service
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: e2esa-webapp01
