apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-role-binding-01
  namespace: project-ns-01
roleRef:
  kind: Role
  name: e2esa-development-role-01 # Add the role created for deployment
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: <user-name> # add username
  apiGroup: rbac.authorization.k8s.io
