apiVersion: v1
kind: Pod
metadata:
 name: mypod
 labels:
  tire: front-end
  env: dev
spec:
 containers:
  - name: nginx
    image: nginx:latest
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
   - name: log-aggregator
    image: log-aggregator:latest
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
